version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=bdtrab

  mongodb:
    image: docker.io/bitnami/mongodb:7.0
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_DATABASE=test

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
